version: '3.3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
